### ISSUE TITLE
Support indexes and review sql for edge table creation/insertion

### ISSUE THREAD

**Issue by Kieranties** [CluedIn-io/CluedIn.Connector.SqlServer#12]
@jurgelionis has identified some scenarios that are impacting the performance of streams.  

### Requirements
1. Support indexes on the edge table
The edge table is created when the user configures the stream export to also publish edges for entities.  The table should be updated to support indexes to improve lookup efficiency
The following is an example sql script that was applied to a customers install to add indexes
```
ALTER TABLE dbo.KontaktEkspressProductLJU ALTER COLUMN OriginEntityCode NVARCHAR(1024) 
ALTER TABLE dbo.kontaktekspresslju ALTER COLUMN OriginEntityCode NVARCHAR(1024) 
ALTER TABLE dbo.kontaktekspressljuEdges ALTER COLUMN OriginEntityCode NVARCHAR(1024) 
ALTER TABLE dbo.kontaktekspressProductljuEdges ALTER COLUMN OriginEntityCode NVARCHAR(1024) 

CREATE UNIQUE INDEX idx_entityCode
ON dbo.kontaktekspresslju (OriginEntityCode); 
CREATE UNIQUE INDEX idx_entityCode
ON dbo.KontaktEkspressProductLJU (OriginEntityCode); 
CREATE INDEX idx_entityCode
ON dbo.KontaktEkspressProductLJUEdges (OriginEntityCode); 
CREATE INDEX idx_entityCode
ON dbo.KontaktEkspressLJUEdges (OriginEntityCode); 
```

2. Review the sql used for CRUD actions on the edge table.
It was originally written by @Kieranties so is probably terrible.  If possible perform updates in a more performant manner.

**Comment by BenFidge** [comment]
@Kieranties Done?
